route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 24h
  receiver: 'mail'

receivers:
  - name: 'mail'
    email_configs:
      - smarthost: 'smtp.gmail.com:587'
        auth_username: 'entel.api@gmail.com'
        auth_identity: 'entel.api@gmail.com'
        auth_password: "pbcixxqgrdkajhpi"
        from: 'entel.api@gmail.com'
        to: 'miguel.mateos@estudiantat.upc.edu'
        require_tls: true

# route:
#   receiver: 'webhook'

# receivers:
#   - name: 'webhook'
#     webhook_configs:
#       - url: 'http://grafana:3000/api/alertmanager'
