name: Simple Workflow

on:
  workflow_dispatch:  # This event triggers the workflow manually

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Server
        run: |
          docker-compose up -d
          #chmod +x script.sh
          #./script.sh